version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: langchain-agent-hub:latest
    env_file:
      - .env
    environment:
      - OPENAI_API_KEY
      - AEMET_API_KEY
    volumes:
      - ./vectorstores:/app/vectorstores
    ports:
      - "8000:8000"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    restart: unless-stopped
